# Generated by Django 3.2.12 on 2023-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('logs', '0001_initial'), ('logs', '0002_auto_20230430_1301'), ('logs', '0003_auto_20230430_1526'), ('logs', '0004_apilog_ip_address'), ('logs', '0005_requestlog'), ('logs', '0006_auto_20230430_1856')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Time of the request')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address of the requestor', null=True)),
                ('user', models.CharField(blank=True, db_index=True, default='', help_text='If captured, the name of the user who sent the request', max_length=255)),
                ('method', models.CharField(blank=True, db_index=True, default='', help_text='HTTP method', max_length=16)),
                ('path', models.CharField(blank=True, db_index=True, default='', help_text='Request path', max_length=255)),
                ('request', models.TextField(default='', help_text='Request body', null=True)),
                ('status_code', models.IntegerField(blank=True, db_index=True, default=None, help_text='Response HTTP status code', null=True)),
                ('exception', models.TextField(blank=True, default=None, help_text='Exception info', null=True)),
                ('duration', models.FloatField(default=0.0, help_text='Duration of the response')),
            ],
        ),
    ]
