# Generated by Django 3.2.25 on 2025-01-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='path_full',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Request path', max_length=255),
        ),
    ]
