# Generated by Django 2.1.2 on 2018-10-01 20:44

import back.models.domain
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epp_id', models.CharField(max_length=32, null=True, unique=True)),
                ('person_name', models.CharField(blank=True, default='', max_length=255)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('address_street', models.CharField(blank=True, default='', max_length=255)),
                ('address_city', models.CharField(blank=True, default='', max_length=255)),
                ('address_province', models.CharField(blank=True, default='', max_length=255)),
                ('address_postal_code', models.CharField(blank=True, default='', max_length=255)),
                ('address_country', models.CharField(blank=True, default='', max_length=255)),
                ('contact_voice', models.CharField(blank=True, default='', max_length=255)),
                ('contact_fax', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('contacts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[back.models.domain.validate])),
                ('expiry_date', models.DateTimeField()),
                ('create_date', models.DateTimeField()),
                ('epp_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('auth_key', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_domains', to='back.Contact')),
                ('contact_billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_domains', to='back.Contact')),
                ('contact_tech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_domains', to='back.Contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
                ('registrant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrant_domains', to='back.Contact')),
            ],
            managers=[
                ('domains', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, default='', max_length=255)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('address_street', models.CharField(blank=True, default='', max_length=255)),
                ('address_city', models.CharField(blank=True, default='', max_length=255)),
                ('address_province', models.CharField(blank=True, default='', max_length=255)),
                ('address_postal_code', models.CharField(blank=True, default='', max_length=255)),
                ('address_country', models.CharField(blank=True, default='', max_length=255)),
                ('contact_voice', models.CharField(blank=True, default='', max_length=255)),
                ('contact_fax', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epp_id', models.CharField(max_length=32, unique=True)),
            ],
            managers=[
                ('registrars', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            managers=[
                ('zones', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='registrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='back.Registrar'),
        ),
        migrations.AddField(
            model_name='domain',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='back.Zone'),
        ),
    ]
