# Generated by Django 2.0.5 on 2018-06-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_first_name', models.CharField(default='', max_length=255)),
                ('person_last_name', models.CharField(default='', max_length=255)),
                ('organization_name', models.CharField(default='', max_length=255)),
                ('address_street', models.CharField(default='', max_length=255)),
                ('address_city', models.CharField(default='', max_length=255)),
                ('address_province', models.CharField(default='', max_length=255)),
                ('address_postal_code', models.CharField(default='', max_length=255)),
                ('address_country', models.CharField(default='', max_length=255)),
                ('contact_voice', models.CharField(default='', max_length=255)),
                ('contact_fax', models.CharField(default='', max_length=255)),
                ('contact_email', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
