# Generated by Django 2.1.2 on 2018-10-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameserver',
            name='owner',
        ),
        migrations.DeleteModel(
            name='NameServer',
        ),
    ]
