# Generated by Django 2.1.1 on 2018-09-27 12:57

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'base_manager_name': 'users', 'default_manager_name': 'users'},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('users', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
