# Generated by Django 2.1.1 on 2018-09-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20180927_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='contact_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_domains', to='back.Contact'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='contact_billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_domains', to='back.Contact'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='contact_tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_domains', to='back.Contact'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registrant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrant_domains', to='back.Contact'),
        ),
    ]
