# Generated by Django 2.1.5 on 2019-01-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_domain_epp_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'base_manager_name': 'domains', 'default_manager_name': 'domains', 'ordering': ['expiry_date']},
        ),
    ]
