# Generated by Django 2.1.2 on 2018-10-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20181022_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'base_manager_name': 'domains', 'default_manager_name': 'domains'},
        ),
    ]
