# Generated by Django 2.1.2 on 2018-10-22 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0005_auto_20181022_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('epp_id', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameservers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'nameservers',
                'default_manager_name': 'nameservers',
            },
            managers=[
                ('nameservers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='epp_id',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='epp_id',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains1', to='back.NameServer'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains2', to='back.NameServer'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains3', to='back.NameServer'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains4', to='back.NameServer'),
        ),
    ]
