# Generated by Django 2.1.2 on 2018-10-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20181022_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameserver',
            name='epp_id',
        ),
    ]
