# Generated by Django 2.1.5 on 2019-02-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20190209_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='epp_status',
            field=models.CharField(choices=[('inactive', 'INACTIVE'), ('deactivated', 'DEACTIVATED'), ('client_hold', 'CLIENT HOLD'), ('server_hold', 'SERVER HOLD'), ('to_be_deleted', 'TO BE DELETED'), ('to_be_restored', 'TO BE RESTORED'), ('unknown', 'UNKNOWN'), ('active', 'ACTIVE')], default='inactive', max_length=32),
        ),
    ]
