# Generated by Django 2.1.2 on 2018-10-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_remove_nameserver_epp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameserver',
            name='host',
            field=models.CharField(max_length=255),
        ),
    ]
