# Generated by Django 2.2 on 2019-04-25 10:49

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_auto_20190302_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='epp_statuses',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
