# Generated by Django 2.2 on 2019-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_domain_epp_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='epp_status',
        ),
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('inactive', 'INACTIVE'), ('to_be_deleted', 'TO BE DELETED'), ('to_be_restored', 'TO BE RESTORED'), ('unknown', 'UNKNOWN'), ('active', 'ACTIVE')], default='inactive', max_length=32),
        ),
    ]
