# Generated by Django 2.2.4 on 2019-09-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_auto_20190602_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_province',
            field=models.CharField(blank=True, max_length=255, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Organization'),
        ),
    ]
