# Generated by Django 2.2.4 on 2019-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_profile_email_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Email notifications enabled'),
        ),
    ]
