# Generated by Django 2.2.9 on 2020-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_auto_20191106_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('inactive', 'INACTIVE'), ('to_be_deleted', 'TO BE DELETED'), ('to_be_restored', 'TO BE RESTORED'), ('suspended', 'SUSPENDED'), ('blocked', 'BLOCKED'), ('unknown', 'UNKNOWN'), ('active', 'ACTIVE')], default='inactive', max_length=32),
        ),
    ]
