# Generated by Django 2.2.10 on 2020-02-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_auto_20200229_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='automatic_renewal_enabled',
            field=models.BooleanField(default=False, verbose_name='Automatically renew expiring domains'),
        ),
    ]
