# Generated by Django 2.2.10 on 2020-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_profile_automatic_renewal_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='auto_renew_enabled',
            field=models.BooleanField(default=True, help_text='Domain will be automatically renewed 3 months before the expiration date, if you have enough funds.', verbose_name='Automatically renew'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='automatic_renewal_enabled',
            field=models.BooleanField(default=True, help_text='Your domains will be automatically renewed 3 months before the expiration date, if you have enough funds.', verbose_name='Automatically renew expiring domains'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable email notifications about expiring domains and low balance.', verbose_name='Email notifications'),
        ),
    ]
