# Generated by Django 2.2.10 on 2020-03-04 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0023_auto_20200304_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_voice',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_voice',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='address_province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='contact_voice',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization'),
        ),
    ]
