# Generated by Django 3.2.12 on 2022-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0028_auto_20201219_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
