# Generated by Django 3.2.12 on 2022-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0029_domain_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='latest_sync_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
