# Generated by Django 3.2.25 on 2025-01-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0030_domain_latest_sync_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='epp_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='epp_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='epp_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='epp_id',
            field=models.CharField(blank=True, default=None, max_length=64, unique=True),
        ),
    ]
