# Generated by Django 3.2.25 on 2025-01-18 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0031_auto_20250116_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123.4567890'. The number must include the country code, which is separated from the phone number (up to 14 digits allowed) by a period.", regex='^\\+[0-9]{1,3}\\.?[0-9]{1,14}$')], verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_voice',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123.4567890'. The number must include the country code, which is separated from the phone number (up to 14 digits allowed) by a period.", regex='^\\+[0-9]{1,3}\\.?[0-9]{1,14}$')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123.4567890'. The number must include the country code, which is separated from the phone number (up to 14 digits allowed) by a period.", regex='^\\+[0-9]{1,3}\\.?[0-9]{1,14}$')], verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_voice',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123.4567890'. The number must include the country code, which is separated from the phone number (up to 14 digits allowed) by a period.", regex='^\\+[0-9]{1,3}\\.?[0-9]{1,14}$')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123.4567890'. The number must include the country code, which is separated from the phone number (up to 14 digits allowed) by a period.", regex='^\\+[0-9]{1,3}\\.?[0-9]{1,14}$')], verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='contact_voice',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123.4567890'. The number must include the country code, which is separated from the phone number (up to 14 digits allowed) by a period.", regex='^\\+[0-9]{1,3}\\.?[0-9]{1,14}$')], verbose_name='Mobile'),
        ),
    ]
