# Generated by Django 3.2.25 on 2025-02-16 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_orderitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0032_auto_20250118_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackEndRenew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('processed', 'Processed')], default='started', max_length=16)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='back.domain', verbose_name='Back-End Renewals')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to=settings.AUTH_USER_MODEL)),
                ('renew_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='billing.order')),
            ],
            options={
                'base_manager_name': 'renewals',
                'default_manager_name': 'renewals',
            },
            managers=[
                ('renewals', django.db.models.manager.Manager()),
            ],
        ),
    ]
