# Generated by Django 3.2.25 on 2025-02-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0033_backendrenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendrenew',
            name='previous_expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
