# Generated by Django 3.2.25 on 2025-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0034_backendrenew_previous_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendrenew',
            name='next_expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
