# Generated by Django 3.2.25 on 2025-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0035_backendrenew_next_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendrenew',
            name='insufficient_balance_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='backendrenew',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='started', max_length=16),
        ),
    ]
