# Generated by Django 3.2.25 on 2025-05-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0038_backendrenew_restore_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='auto_renew_enabled',
            field=models.BooleanField(default=True, help_text='Domain will be automatically renewed 3 months before the expiration date, if you have enough funds. Account balance will be automatically deducted.', verbose_name='Automatically renew'),
        ),
    ]
