# Generated by Django 3.2.25 on 2025-05-29 17:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0039_alter_domain_auto_renew_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendrenew',
            name='details',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='backendrenew',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='started', max_length=16),
        ),
    ]
