# Generated by Django 3.2.25 on 2025-06-13 08:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0040_auto_20250529_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='extension_info',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
