# Generated by Django 3.2.25 on 2025-06-28 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0041_domain_extension_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_email',
            field=models.CharField(help_text='Click <a href="email-test/">here</a> to check the delivery of service messages, we will send you a test email.', max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
