# Generated by Django 3.2.25 on 2025-08-27 16:08

from django.db import migrations, models
import django.db.models.manager
import zen.zdomains


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0042_alter_profile_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[zen.zdomains.validate_domain_name])),
            ],
            options={
                'base_manager_name': 'blocked_transfers',
                'default_manager_name': 'blocked_transfers',
            },
            managers=[
                ('blocked_transfers', django.db.models.manager.Manager()),
            ],
        ),
    ]
