version: 2.1
executors:
  my-machine-executor:
    machine:
      image: default

jobs:
  zenaida-job:

    executor: my-machine-executor
    steps:
      - checkout
      - run:
          name: "Use Docker Compose"
          command: |
            docker-compose -v
      - run:
          name: "Build"
          command: |
            make docker/test

workflows:
  build:
    jobs:
      - zenaida-job:
          filters:
            branches:
              ignore: master
