version: 2.1
jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: "Use Docker Compose"
          command: |
            docker-compose -v
      - run:
          name: "Build"
          command: |
            make docker/test
