# Generated by Django 2.1.2 on 2019-01-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('pay_4csonline', 'Credit Card'), ('pay_bank_transfer_anguilla', 'Bank Transfer')], max_length=32)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('failed', 'Failed'), ('paid', 'Paid'), ('processed', 'Processed')], default='started', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'payments',
                'default_manager_name': 'payments',
            },
            managers=[
                ('payments', django.db.models.manager.Manager()),
            ],
        ),
    ]
