# Generated by Django 2.1.5 on 2019-01-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190120_1549'),
        ('billing', '0003_auto_20190120_2150'),
    ]

    operations = [
    ]
