# Generated by Django 2.1.5 on 2019-01-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_merge_20190120_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('paid', 'Paid'), ('unconfirmed', 'Unconfirmed'), ('processed', 'Processed')], default='started', max_length=16),
        ),
    ]
