# Generated by Django 2.1.5 on 2019-01-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20190120_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
