# Generated by Django 2.1.5 on 2019-01-27 15:13

from django.db import migrations, models

import zen.zdomains


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=255, validators=[zen.zdomains.validate_domain_name]),
        ),
    ]
