# Generated by Django 2.1.5 on 2019-01-27 15:13

import back.domains
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=255, validators=[back.domains.validate]),
        ),
    ]
