# Generated by Django 2.1.5 on 2019-02-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('processed', 'Processed')], default='started', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('processed', 'Processed')], default='started', max_length=16),
        ),
    ]
