# Generated by Django 2.2 on 2019-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20190202_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('pay_4csonline', 'Credit Card'), ('pay_bank_transfer_anguilla', 'Bank Transfer'), ('pay_btcpay', 'BitCoin')], max_length=32),
        ),
    ]
