# Generated by Django 2.2.2 on 2019-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_btcpayinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('pay_4csonline', 'Credit Card'), ('pay_btcpay', 'BitCoin')], max_length=32),
        ),
    ]
