# Generated by Django 2.2.3 on 2019-08-11 20:30

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20190705_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(choices=[('domain_register', 'Domain Register'), ('domain_renew', 'Domain Renew'), ('domain_restore', 'Domain Restore'), ('domain_transfer', 'Domain Transfer')], max_length=32),
        ),
    ]
