# Generated by Django 3.1.4 on 2021-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_auto_20201219_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=None, help_text='any note regarding the payment such as the reason of the balance change by admin.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('pay_4csonline', 'Credit Card'), ('pay_btcpay', 'BitCoin'), ('pay_by_admin', 'Pay by Admin')], max_length=32),
        ),
    ]
