# Generated by Django 3.1.4 on 2021-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20210123_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('pay_4csonline', 'Credit Card'), ('pay_btcpay', 'BitCoin'), ('pay_by_admin', 'Balance adjustment by admin')], max_length=32),
        ),
    ]
