# Generated by Django 3.2.5 on 2022-01-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20210124_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('pending', 'Pending'), ('executing', 'Executing'), ('failed', 'Failed'), ('processed', 'Processed')], default='started', max_length=16),
        ),
    ]
