# Generated by Django 3.2.25 on 2026-03-08 11:27

from django.db import migrations, models
import zen.zdomains


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='duration',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[zen.zdomains.validate_domain_name]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('pending', 'Pending'), ('executing', 'Executing'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('processed', 'Processed')], db_index=True, default='started', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(choices=[('domain_register', 'Domain Register'), ('domain_renew', 'Domain Renew'), ('domain_restore', 'Domain Restore'), ('domain_transfer', 'Domain Transfer')], db_index=True, max_length=32),
        ),
    ]
