# Generated by Django 2.2.4 on 2019-10-30 10:20

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190203_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('sent', 'SENT'), ('failed', 'FAILED')], default='started', max_length=10)),
                ('type', models.CharField(choices=[('email', 'EMAIL'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(choices=[('domain_expiring', 'DOMAIN EXPIRING'), ('domain_restored', 'DOMAIN RESTORED'), ('domain_transferred', 'DOMAIN TRANSFERRED'), ('domain_activated', 'DOMAIN ACTIVATED'), ('domain_deactivated', 'DOMAIN DEACTIVATED')], max_length=32)),
                ('domain_name', models.CharField(max_length=255)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'notifications',
                'default_manager_name': 'notifications',
            },
            managers=[
                ('notifications', django.db.models.manager.Manager()),
            ],
        ),
    ]
