# Generated by Django 2.2.10 on 2020-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('domain_expiring', 'DOMAIN EXPIRING'), ('domain_expire_soon', 'DOMAIN EXPIRE SOON'), ('domain_restored', 'DOMAIN RESTORED'), ('domain_transferred', 'DOMAIN TRANSFERRED'), ('domain_activated', 'DOMAIN ACTIVATED'), ('domain_deactivated', 'DOMAIN DEACTIVATED'), ('domain_renewed', 'DOMAIN RENEWED'), ('low_balance', 'LOW BALANCE')], max_length=32),
        ),
    ]
