# Generated by Django 3.1.4 on 2020-12-19 14:51

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200504_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='details',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
