# Generated by Django 3.2.25 on 2024-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('started', 'STARTED'), ('sent', 'SENT'), ('failed', 'FAILED'), ('skipped', 'SKIPPED')], default='started', max_length=10),
        ),
    ]
