# Generated by Django 3.2.25 on 2025-01-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('domain_expiring', 'DOMAIN EXPIRING'), ('domain_expire_soon', 'DOMAIN EXPIRE SOON'), ('domain_restored', 'DOMAIN RESTORED'), ('domain_transferred', 'DOMAIN TRANSFERRED'), ('domain_activated', 'DOMAIN ACTIVATED'), ('domain_deactivated', 'DOMAIN DEACTIVATED'), ('domain_renewed', 'DOMAIN RENEWED'), ('low_balance', 'LOW BALANCE'), ('account_approved', 'ACCOUNT_APPROVED')], max_length=32),
        ),
    ]
