# Generated by Django 3.2.25 on 2025-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_notification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('domain_expiring', 'DOMAIN EXPIRING'), ('domain_expire_soon', 'DOMAIN EXPIRE SOON'), ('domain_restored', 'DOMAIN RESTORED'), ('domain_transferred', 'DOMAIN TRANSFERRED'), ('domain_activated', 'DOMAIN ACTIVATED'), ('domain_deactivated', 'DOMAIN DEACTIVATED'), ('domain_renewed', 'DOMAIN RENEWED'), ('domain_deleted', 'DOMAIN DELETED'), ('low_balance', 'LOW BALANCE'), ('low_balance_back_end_renew', 'LOW BALANCE BACK END RENEW'), ('account_approved', 'ACCOUNT_APPROVED')], max_length=32),
        ),
    ]
