"""
Country codes and labels.
"""

def codes():
    return {
        'afghanistan': 'AF',
        'aland': 'AX',
        'albania': 'AL',
        'algeria': 'DZ',
        'american samoa': 'AS',
        'andorra': 'AD',
        'angola': 'AO',
        'anguilla': 'AI',
        'antigua and barbuda': 'AG',
        'argentina': 'AR',
        'armenia': 'AM',
        'aruba': 'AW',
        'ascension': 'AC',
        'australia': 'AU',
        'austria': 'AT',
        'azerbaijan': 'AZ',
        'bahamas': 'BS',
        'bahrain': 'BH',
        'bangladesh': 'BD',
        'barbados': 'BB',
        'belarus': 'BY',
        'belgium': 'BE',
        'belize': 'BZ',
        'benin': 'BJ',
        'bermuda': 'BM',
        'bhutan': 'BT',
        'bolivia': 'BO',
        'bosnia and herzegovina': 'BA',
        'botswana': 'BW',
        'bouvet island': 'BV',
        'brazil': 'BR',
        'british antarctic territory': 'AQ',
        'british indian ocean territory': 'IO',
        'british virgin islands': 'VG',
        'brunei': 'BN',
        'bulgaria': 'BG',
        'burkina faso': 'BF',
        'burundi': 'BI',
        'cambodia': 'KH',
        'cameroon': 'CM',
        'canada': 'CA',
        'cape verde': 'CV',
        'cayman islands': 'KY',
        'central african republic': 'CF',
        'chad': 'TD',
        'chile': 'CL',
        'china': 'CN',
        'christmas island': 'CX',
        'cocos islands': 'CC',
        'colombia': 'CO',
        'comoros': 'KM',
        'congo brazzaville': 'CG',
        'congo kinshasa': 'CD',
        'cook islands': 'CK',
        'costa rica': 'CR',
        "cote d'ivoire": 'CI',
        'croatia': 'HR',
        'cuba': 'CU',
        'czech republic': 'CZ',
        'denmark': 'DK',
        'djibouti': 'DJ',
        'dominica': 'DM',
        'dominican republic': 'DO',
        'ecuador': 'EC',
        'egypt': 'EG',
        'el salvador': 'SV',
        'equatorial guinea': 'GQ',
        'eritrea': 'ER',
        'estonia': 'EE',
        'ethiopia': 'ET',
        'falkland islands': 'FK',
        'faroe islands': 'FO',
        'fiji': 'FJ',
        'finland': 'FI',
        'france': 'FR',
        'french guiana': 'GF',
        'french polynesia': 'PF',
        'french southern and antarctic lands': 'TF',
        'gabon': 'GA',
        'gambia': 'GM',
        'georgia': 'GE',
        'germany': 'DE',
        'ghana': 'GH',
        'gibraltar': 'GI',
        'greece': 'GR',
        'greenland': 'GL',
        'grenada': 'GD',
        'guadeloupe': 'GP',
        'guam': 'GU',
        'guatemala': 'GT',
        'guernsey': 'GG',
        'guinea': 'GN',
        'guinea-bissau': 'GW',
        'guyana': 'GY',
        'haiti': 'HT',
        'heard island and mcdonald islands': 'HM',
        'honduras': 'HN',
        'hong kong': 'HK',
        'hungary': 'HU',
        'iceland': 'IS',
        'india': 'IN',
        'indonesia': 'ID',
        'iran': 'IR',
        'iraq': 'IQ',
        'ireland': 'IE',
        'isle of man': 'IM',
        'israel': 'IL',
        'italy': 'IT',
        'jamaica': 'JM',
        'japan': 'JP',
        'jersey': 'JE',
        'jordan': 'JO',
        'kazakhstan': 'KZ',
        'kenya': 'KE',
        'kiribati': 'KI',
        'kuwait': 'KW',
        'kyrgyzstan': 'KG',
        'laos': 'LA',
        'latvia': 'LV',
        'lebanon': 'LB',
        'lesotho': 'LS',
        'liberia': 'LR',
        'libya': 'LY',
        'liechtenstein': 'LI',
        'lithuania': 'LT',
        'luxembourg': 'LU',
        'macau': 'MO',
        'macedonia': 'MK',
        'madagascar': 'MG',
        'malawi': 'MW',
        'malaysia': 'MY',
        'maldives': 'MV',
        'mali': 'ML',
        'malta': 'MT',
        'marshall islands': 'MH',
        'martinique': 'MQ',
        'mauritania': 'MR',
        'mauritius': 'MU',
        'mayotte': 'YT',
        'mexico': 'MX',
        'micronesia': 'FM',
        'moldova': 'MD',
        'monaco': 'MC',
        'mongolia': 'MN',
        'montenegro': 'ME',
        'montserrat': 'MS',
        'morocco': 'MA',
        'mozambique': 'MZ',
        'myanmar': 'MM',
        'namibia': 'NA',
        'nauru': 'NR',
        'nepal': 'NP',
        'netherlands': 'NL',
        'netherlands antilles': 'AN',
        'new caledonia': 'NC',
        'new zealand': 'NZ',
        'nicaragua': 'NI',
        'niger': 'NE',
        'nigeria': 'NG',
        'niue': 'NU',
        'norfolk island': 'NF',
        'north korea': 'KP',
        'cyprus': 'CY',
        'northern mariana islands': 'MP',
        'norway': 'NO',
        'oman': 'OM',
        'pakistan': 'PK',
        'palau': 'PW',
        'panama': 'PA',
        'papua new guinea': 'PG',
        'paraguay': 'PY',
        'peru': 'PE',
        'philippines': 'PH',
        'pitcairn islands': 'PN',
        'poland': 'PL',
        'portugal': 'PT',
        'puerto rico': 'PR',
        'qatar': 'QA',
        'reunion': 'RE',
        'romania': 'RO',
        'russia': 'RU',
        'rwanda': 'RW',
        'saint helena': 'SH',
        'saint kitts and nevis': 'KN',
        'saint lucia': 'LC',
        'saint pierre and miquelon': 'PM',
        'saint vincent and the grenadines': 'VC',
        'samoa': 'WS',
        'san marino': 'SM',
        'sao tome and principe': 'ST',
        'saudi arabia': 'SA',
        'senegal': 'SN',
        'serbia': 'RS',
        'seychelles': 'SC',
        'sierra leone': 'SL',
        'singapore': 'SG',
        'slovakia': 'SK',
        'slovenia': 'SI',
        'solomon islands': 'SB',
        'somalia': 'SO',
        'south africa': 'ZA',
        'south georgia & south sandwich islands': 'GS',
        'south korea': 'KR',
        'spain': 'ES',
        'sri lanka': 'LK',
        'sudan': 'SD',
        'suriname': 'SR',
        'svalbard': 'SJ',
        'swaziland': 'SZ',
        'sweden': 'SE',
        'switzerland': 'CH',
        'syria': 'SY',
        'taiwan': 'TW',
        'tajikistan': 'TJ',
        'tanzania': 'TZ',
        'thailand': 'TH',
        'timor-leste': 'TL',
        'togo': 'TG',
        'tokelau': 'TK',
        'tonga': 'TO',
        'trinidad and tobago': 'TT',
        'tristan da cunha': 'TA',
        'tunisia': 'TN',
        'turkey': 'TR',
        'turkmenistan': 'TM',
        'turks and caicos islands': 'TC',
        'tuvalu': 'TV',
        'u.s. virgin islands': 'VI',
        'uganda': 'UG',
        'ukraine': 'UA',
        'united arab emirates': 'AE',
        'united kingdom': 'GB',
        'united states': 'US',
        'uruguay': 'UY',
        'uzbekistan': 'UZ',
        'vanuatu': 'VU',
        'vatican city': 'VA',
        'venezuela': 'VE',
        'vietnam': 'VN',
        'wallis and futuna': 'WF',
        'yemen': 'YE',
        'zambia': 'ZM',
        'zimbabwe': 'ZW'
    }


def labels():
    return {
        'AC': 'Ascension',
        'AD': 'Andorra',
        'AE': 'United Arab Emirates',
        'AF': 'Afghanistan',
        'AG': 'Antigua and Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AN': 'Netherlands Antilles',
        'AO': 'Angola',
        'AQ': 'British Antarctic Territory',
        'AR': 'Argentina',
        'AS': 'American Samoa',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Aland',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia and Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgium',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BM': 'Bermuda',
        'BN': 'Brunei',
        'BO': 'Bolivia',
        'BR': 'Brazil',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Bouvet Island',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Canada',
        'CC': 'Cocos Islands',
        'CD': 'Congo Kinshasa',
        'CF': 'Central African Republic',
        'CG': 'Congo Brazzaville',
        'CH': 'Switzerland',
        'CI': "Cote d'Ivoire",
        'CK': 'Cook Islands',
        'CL': 'Chile',
        'CM': 'Cameroon',
        'CN': "China",
        'CO': 'Colombia',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CX': 'Christmas Island',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DE': 'Germany',
        'DJ': 'Djibouti',
        'DK': 'Denmark',
        'DM': 'Dominica',
        'DO': 'Dominican Republic',
        'DZ': 'Algeria',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egypt',
        'ER': 'Eritrea',
        'ES': 'Spain',
        'ET': 'Ethiopia',
        'FI': 'Finland',
        'FJ': 'Fiji',
        'FK': 'Falkland Islands',
        'FM': 'Micronesia',
        'FO': 'Faroe Islands',
        'FR': 'France',
        'GA': 'Gabon',
        'GB': 'United Kingdom',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'French Guiana',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Equatorial Guinea',
        'GR': 'Greece',
        'GS': 'South Georgia & South Sandwich Islands',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong',
        'HM': 'Heard Island and McDonald Islands',
        'HN': 'Honduras',
        'HR': 'Croatia',
        'HT': 'Haiti',
        'HU': 'Hungary',
        'ID': 'Indonesia',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'India',
        'IO': 'British Indian Ocean Territory',
        'IQ': 'Iraq',
        'IR': 'Iran',
        'IS': 'Iceland',
        'IT': 'Italy',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordan',
        'JP': 'Japan',
        'KE': 'Kenya',
        'KG': 'Kyrgyzstan',
        'KH': 'Cambodia',
        'KI': 'Kiribati',
        'KM': 'Comoros',
        'KN': 'Saint Kitts and Nevis',
        'KP': 'North Korea',
        'KR': 'South Korea',
        'KW': 'Kuwait',
        'KY': 'Cayman Islands',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lebanon',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'LY': 'Libya',
        'MA': 'Morocco',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MG': 'Madagascar',
        'MH': 'Marshall Islands',
        'MK': 'Macedonia',
        'ML': 'Mali',
        'MM': 'Myanmar',
        'MN': 'Mongolia',
        'MO': 'Macau',
        'MP': 'Northern Mariana Islands',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexico',
        'MY': 'Malaysia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'New Caledonia',
        'NE': 'Niger',
        'NF': 'Norfolk Island',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Netherlands',
        'NO': 'Norway',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'New Zealand',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'French Polynesia',
        'PG': 'Papua New Guinea',
        'PH': 'Philippines',
        'PK': 'Pakistan',
        'PL': 'Poland',
        'PM': 'Saint Pierre and Miquelon',
        'PN': 'Pitcairn Islands',
        'PR': 'Puerto Rico',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Reunion',
        'RO': 'Romania',
        'RS': 'Serbia',
        'RU': 'Russia',
        'RW': 'Rwanda',
        'SA': 'Saudi Arabia',
        'SB': 'Solomon Islands',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Sweden',
        'SG': 'Singapore',
        'SH': 'Saint Helena',
        'SI': 'Slovenia',
        'SJ': 'Svalbard',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'ST': 'Sao Tome and Principe',
        'SV': 'El Salvador',
        'SY': 'Syria',
        'SZ': 'Swaziland',
        'TA': 'Tristan da Cunha',
        'TC': 'Turks and Caicos Islands',
        'TD': 'Chad',
        'TF': 'French Southern and Antarctic Lands',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-Leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TR': 'Turkey',
        'TT': 'Trinidad and Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'US': 'United States',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Vatican City',
        'VC': 'Saint Vincent and the Grenadines',
        'VE': 'Venezuela',
        'VG': 'British Virgin Islands',
        'VI': 'U.S. Virgin Islands',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis and Futuna',
        'WS': 'Samoa',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'South Africa',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe'
    }


def get_country_code(country_label, default='GB'):
    if country_label.upper() in labels().keys():
        return country_label.upper()
    return codes().get(country_label.lower(), default)


def get_country_label(country_code, default='United Kingdom'):
    if country_code.lower() in codes().keys():
        return country_code
    return labels().get(country_code, default)


def clean_country_code(cc):
    cc = cc.replace('UK', 'GB')
    return cc
